
select * from customer limit 20

--Q1: What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) as revenue 
from customer
group by gender

--Q2: which customers used a discount but still spent more than the average purchase amount
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select Avg(purchase_amount) from customer)

--Q3: Which are thr top 5 products with the highest avg review rating?
select item_purchased, round(avg(review_rating::numeric),2) as "Avg Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

--Q4: Compare the avg purchase amts b/w std and express shipping
select shipping_type, 
round(avg(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

--Q5: do subscribed customers spend more? compare avg spend & total revenue b/w subscriber & non-s
select subscription_status,
count(customer_id) as total_customer,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc

--Q6: which 5 products have the highest % of purchases with discount applied?
select item_purchased,
Round(100*sum(case when discount_applied = 'Yes' then 1 else 0 end)/ count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5

--Q7: segment customers into new,returning & loyal based on their total no. of pervious purchase, 
--& show the count of each segment
with customer_type as (
select customer_id , previous_purchases,
case 
	when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
	end as customer_segement
from customer
)

select customer_segement, count(*) as "No. of Customer"
from customer_type
group by customer_segement

--Q8: what are the top 3 most purchased products within each category?
with item_counts as (
select category, item_purchased, count(customer_id) as total_orders,
Row_number() over (partition by category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased
)
select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank <= 3;

--Q9: are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status, count(customer_id) as repeat_buyers 
from customer
where previous_purchases >5
group by subscription_status

--Q10: what is the revenue contribution of each age grp?
select age_group, Sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;

